import { Stack } from "expo-router";
import { ScrollView, View } from "react-native";
import Markdown from "react-native-markdown-display";

const privacyPolicy = `
# Privacy Policy

_Last updated: November 10, 2022_

This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service. It also informs You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.

## Interpretation and Definitions

### Interpretation

Words with capitalized initial letters have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.

### Definitions

- **Account**: A unique account created for You to access our Service or parts of our Service.
- **Affiliate**: An entity that controls, is controlled by, or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.
- **Application**: The software program provided by the Company, downloaded by You on any electronic device, named Live Timeless.
- **Company**: Refers to Live Timeless, 700 4 Ave SW, Calgary, Alberta, Canada. In this Agreement, the Company may also be referred to as “We,” “Us,” or “Our.”
- **Country**: Refers to Alberta, Canada.
- **Device**: Any device that can access the Service, such as a computer, cellphone, or tablet.
- **Personal Data**: Information that relates to an identified or identifiable individual.
- **Service**: Refers to the Application.
- **Service Provider**: Any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate or analyze the Service.
- **Third-party Social Media Service**: Any website or social network website through which a User can log in or create an account to use the Service.
- **Usage Data**: Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (e.g., the duration of a page visit).
- **You**: The individual accessing or using the Service, or the legal entity on whose behalf such an individual is accessing or using the Service.

## Collecting and Using Your Personal Data

### Types of Data Collected

#### Personal Data

While using Our Service, We may ask You to provide certain personally identifiable information, which may include:

- Email address
- First and last name
- Phone number
- Usage Data

#### Usage Data

Usage Data is collected automatically when using the Service. It may include details such as Your Device’s Internet Protocol (IP) address, browser type, pages visited, and other diagnostic data. Additionally, if You use a mobile device, We may collect details such as device type, unique device ID, and mobile operating system.

### Information from Third-Party Social Media Services

If You log in via Google, Facebook, Twitter, LinkedIn, or other platforms, We may collect Personal Data associated with Your Third-Party Social Media Service account, such as name, email, and contact list.

### Information Collected while Using the Application

We may collect, with Your permission, data from Your device’s phone book, camera, or photo library to provide features within the Service.

### Use of Your Personal Data

The Company may use Personal Data for the following purposes:

- To provide and maintain our Service
- To manage Your Account
- To perform a contract, such as processing purchases
- To contact You via email, phone, or push notifications
- To provide news, offers, or information about related services unless You opt out
- To manage requests or communications
- For business transfers, mergers, or sales of Company assets
- For other purposes like data analysis and improving our services

### Sharing of Your Personal Data

The Company may share Your personal information:

- With Service Providers to monitor and analyze the use of our Service
- For business transfers in the event of a merger, sale, or acquisition
- With affiliates, business partners, or other users
- With Your consent for any other specific purpose

### Retention of Your Personal Data

We retain Your Personal Data only for as long as necessary to fulfill the purposes described in this policy or to comply with legal obligations. Usage Data may be retained for shorter periods unless used for security or functionality improvements.

### Transfer of Your Personal Data

Your data may be transferred to and processed outside Your state or country where data protection laws may differ. We will ensure that Your Personal Data is treated securely.

### Deletion of Your Personal Data

You have the right to delete Your Personal Data or request assistance with deletion. You can manage or delete Your data from within the Service or by contacting Us.

### Disclosure of Your Personal Data

We may disclose Personal Data in the following circumstances:

- For business transactions, such as mergers or acquisitions
- To comply with legal obligations
- To protect Company rights, public safety, or to prevent wrongdoing

### Security of Your Personal Data

We take commercially reasonable steps to protect Your Personal Data, though no method of transmission over the Internet is 100% secure.

## Children's Privacy

Our Service does not address anyone under the age of 13. We do not knowingly collect information from anyone under 13. If We learn that We have collected data from someone under 13, We will delete it unless parental consent is provided.

## Links to Other Websites

Our Service may contain links to third-party websites. We are not responsible for their content or privacy practices.

## Changes to this Privacy Policy

We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the updated version on this page and updating the “Last updated” date.

## Contact Us

If you have any questions about this Privacy Policy, contact us:

- **By email**: info@livetimeless.com
- **By visiting our website**: [Live Timeless](https://www.livetimeless.com)
`;

export default function PrivacyPolicy() {
  return (
    <>
      <Stack.Screen
        options={{
          headerTitle: "Privacy Policy",
          headerBackVisible: true,
          headerBackTitleVisible: false,
          headerStyle: {
            backgroundColor: "#082139",
          },
          headerTintColor: "#fff",
        }}
      />
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        style={{
          height: "100%",
          backgroundColor: "white",
          padding: 20,
        }}
      >
        <Markdown>{privacyPolicy}</Markdown>
      </ScrollView>
    </>
  );
}
